import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PHASE_LABELS } from '@/types';
import { useUIStore } from '@/store/uiStore';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { computePhaseDays, getDoctorColor } from '@/lib/sort';
export function PatientCard({ patient, onClick }) {
    const { openModal } = useUIStore();
    const phaseColor = `var(--phase-${patient.phase})`;
    const { label: daysLabel, days } = computePhaseDays(patient);
    return (_jsxs(Card, { className: "flex overflow-hidden hover:shadow-md transition-shadow", hoverable: true, onClick: onClick, children: [_jsx("div", { className: "w-1 flex-shrink-0", style: { backgroundColor: phaseColor } }), _jsxs("div", { className: "flex-1 p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-data text-base font-bold min-w-[2rem]", style: { color: patient.attendingDoctor ? getDoctorColor(patient.attendingDoctor) : 'var(--color-primary)' }, children: patient.bedNumber || '--' }), _jsx("span", { className: "font-bold text-[var(--color-text)]", children: patient.name }), _jsxs("span", { className: "text-sm text-[var(--color-text-secondary)]", children: [patient.gender === 'male' ? '男' : '女', " ", patient.age, "\u5C81"] })] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "font-data text-xs px-1.5 py-0.5 rounded-full text-white", style: { backgroundColor: phaseColor }, children: PHASE_LABELS[patient.phase] }), days > 0 && _jsxs("span", { className: "font-data text-xs text-[var(--color-text-muted)]", children: [daysLabel, days, "\u5929"] }), days === 0 && daysLabel === '手术日' && _jsx("span", { className: "font-data text-xs text-[var(--color-error)]", children: "\u624B\u672F\u65E5" })] })] }), _jsx("p", { className: "text-sm text-[var(--color-text-secondary)] mb-1.5", children: patient.surgery?.surgeryType || patient.diagnosis || '—' }), _jsxs("div", { className: "flex items-center gap-3 text-xs text-[var(--color-text-muted)] mb-1.5", children: [_jsxs("span", { children: ["\u5165\u9662: ", patient.admissionDate] }), patient.surgeryDate && _jsxs("span", { children: ["\u624B\u672F: ", patient.surgeryDate] }), patient.attendingDoctor && _jsxs("span", { children: ["\u4E3B\u7BA1: ", patient.attendingDoctor] })] }), patient.tags.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-1 mb-2", children: patient.tags.map(tag => (_jsx("span", { className: "font-ui text-[10px] px-1.5 py-0.5 rounded-full bg-[var(--color-primary-light)] text-[var(--color-primary)]", children: tag }, tag))) })), _jsxs("div", { className: "flex gap-1.5", onClick: (e) => e.stopPropagation(), children: [_jsx(Button, { size: "sm", variant: "outline", onClick: () => openModal('rounding', { patientId: patient.id, session: 'am' }), children: "\u65E9\u67E5\u623F" }), _jsx(Button, { size: "sm", variant: "outline", onClick: () => openModal('rounding', { patientId: patient.id, session: 'pm' }), children: "\u665A\u67E5\u623F" })] })] })] }));
}
