/**
 * Seed test data. In browser console, run: await (await import('./lib/seed')).seedData()
 */
import { db } from './db';
import { v4 as uid } from 'uuid';
function d(delta = 0) { const d = new Date(); d.setDate(d.getDate() + delta); return d.toISOString().split('T')[0]; }
function iso(delta = 0) { const d = new Date(); d.setDate(d.getDate() + delta); return d.toISOString(); }
export async function seedData() {
    await db.transaction('rw', [db.patients, db.roundingRecords, db.labResults], async () => {
        await db.patients.clear();
        await db.roundingRecords.clear();
        await db.labResults.clear();
    });
    const patients = [
        // ── 术前 ──
        { id: uid(), name: '王建国', gender: 'male', age: 62, mrn: 'M001', bedNumber: '1', diagnosis: '冠心病三支病变', comorbidities: ['高血压', '糖尿病'], admissionDate: d(-3), surgeryDate: d(2), phase: 'pre-op', attendingDoctor: '陈医生', surgery: { surgeryType: 'CABG×4', cathDate: d(-5), cathFindings: 'LAD 90%, LCX 70%, RCA 80%', ctffr: { lad: 0.62, lcx: 0.78, rca: 0.85 } }, tubes: [], tags: ['CABG'], notes: '计划下周二手术', phaseHistory: [{ phase: 'pre-op', date: d(-3) }], archived: false, createdAt: iso(-3), updatedAt: iso(-3) },
        { id: uid(), name: '张秀英', gender: 'female', age: 58, mrn: 'M002', bedNumber: '2', diagnosis: '风湿性心脏病，二尖瓣重度狭窄', comorbidities: ['房颤'], admissionDate: d(-2), surgeryDate: d(3), phase: 'pre-op', attendingDoctor: '陈医生', surgery: { surgeryType: 'MVR（生物瓣）+ TVP' }, tubes: [], tags: ['MVR', '房颤'], notes: '', phaseHistory: [{ phase: 'pre-op', date: d(-2) }], archived: false, createdAt: iso(-2), updatedAt: iso(-2) },
        { id: uid(), name: '李大伟', gender: 'male', age: 45, mrn: 'M003', bedNumber: '3', diagnosis: '主动脉瓣二叶畸形重度狭窄', comorbidities: [], admissionDate: d(-1), surgeryDate: d(1), phase: 'pre-op', attendingDoctor: '刘医生', surgery: { surgeryType: 'AVR（机械瓣）' }, tubes: [], tags: ['AVR'], notes: '年轻，选择机械瓣', phaseHistory: [{ phase: 'pre-op', date: d(-1) }], archived: false, createdAt: iso(-1), updatedAt: iso(-1) },
        { id: uid(), name: '赵明辉', gender: 'male', age: 71, mrn: 'M004', bedNumber: '+1', diagnosis: '冠心病不稳定心绞痛', comorbidities: ['高血压'], admissionDate: d(-2), surgeryDate: d(4), phase: 'pre-op', attendingDoctor: '刘医生', surgery: { surgeryType: 'CABG×3' }, tubes: [], tags: ['CABG'], notes: '', phaseHistory: [{ phase: 'pre-op', date: d(-2) }], archived: false, createdAt: iso(-2), updatedAt: iso(-2) },
        { id: uid(), name: '陈丽华', gender: 'female', age: 67, mrn: 'M005', bedNumber: 'Z1', diagnosis: '感染性心内膜炎主动脉瓣赘生物', comorbidities: [], admissionDate: d(-5), surgeryDate: d(0), phase: 'pre-op', attendingDoctor: '陈医生', surgery: { surgeryType: 'AVR+赘生物清除' }, tubes: [], tags: ['心内膜炎', '急诊'], notes: '万古霉素+庆大霉素抗感染中', phaseHistory: [{ phase: 'pre-op', date: d(-5) }], archived: false, createdAt: iso(-5), updatedAt: iso(-1) },
        // ── 手术日 ──
        { id: uid(), name: '孙志强', gender: 'male', age: 55, mrn: 'M006', bedNumber: '4', diagnosis: 'A型主动脉夹层（Stanford A）', comorbidities: ['高血压3级'], admissionDate: d(-1), surgeryDate: d(0), phase: 'surgery-day', attendingDoctor: '刘医生', surgery: { surgeryType: 'Bentall+全弓置换+象鼻支架', cpbTime: 198, crossClampTime: 145, dhcaTime: 25, intraopComplications: '出血较多，输RBC 8U' }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(0) }, { id: uid(), type: 'arterial-sheath', insertedAt: iso(0) }, { id: uid(), type: 'pericardial-drain', insertedAt: iso(0) }, { id: uid(), type: 'ett', insertedAt: iso(0) }], tags: ['夹层', '急诊', 'Bentall'], notes: '', phaseHistory: [{ phase: 'pre-op', date: d(-1) }, { phase: 'surgery-day', date: d(0) }], archived: false, createdAt: iso(-1), updatedAt: iso(0) },
        { id: uid(), name: '周桂芳', gender: 'female', age: 73, mrn: 'M007', bedNumber: '5', diagnosis: '冠心病三支病变+二尖瓣中度关闭不全', comorbidities: ['糖尿病'], admissionDate: d(-3), surgeryDate: d(0), phase: 'surgery-day', attendingDoctor: '陈医生', surgery: { surgeryType: 'CABG×3+MVP', cpbTime: 156, crossClampTime: 112 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(0) }, { id: uid(), type: 'ett', insertedAt: iso(0) }], tags: ['CABG', 'MVP'], notes: '', phaseHistory: [{ phase: 'pre-op', date: d(-3) }, { phase: 'surgery-day', date: d(0) }], archived: false, createdAt: iso(-3), updatedAt: iso(0) },
        // ── 术后监护 ──
        { id: uid(), name: '吴永康', gender: 'male', age: 68, mrn: 'M008', bedNumber: '6', diagnosis: '冠心病左主干+三支病变', comorbidities: ['高血压', 'COPD'], admissionDate: d(-6), surgeryDate: d(-3), phase: 'post-op-icu', attendingDoctor: '刘医生', surgery: { surgeryType: 'CABG×4', cpbTime: 132, crossClampTime: 95, cmrLgeSegments: 2 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-3), lastDressingAt: iso(-2) }, { id: uid(), type: 'pericardial-drain', insertedAt: iso(-3) }, { id: uid(), type: 'left-chest-tube', insertedAt: iso(-3) }, { id: uid(), type: 'right-chest-tube', insertedAt: iso(-3) }], tags: ['CABG', 'COPD'], notes: 'POD3，已拔管，SBT通过', phaseHistory: [{ phase: 'pre-op', date: d(-6) }, { phase: 'surgery-day', date: d(-3) }, { phase: 'post-op-icu', date: d(-2) }], archived: false, createdAt: iso(-6), updatedAt: iso(-1) },
        { id: uid(), name: '郑美兰', gender: 'female', age: 64, mrn: 'M009', bedNumber: '+2', diagnosis: '主动脉瓣重度狭窄', comorbidities: ['房颤'], admissionDate: d(-5), surgeryDate: d(-2), phase: 'post-op-icu', attendingDoctor: '陈医生', surgery: { surgeryType: 'AVR（生物瓣）+房颤射频消融', cpbTime: 118, crossClampTime: 82 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-2) }, { id: uid(), type: 'arterial-sheath', insertedAt: iso(-2), lastDressingAt: d(-1) }], tags: ['AVR', '房颤'], notes: 'POD2，已拔管，窦性心律，药物减量中', phaseHistory: [{ phase: 'pre-op', date: d(-5) }, { phase: 'surgery-day', date: d(-2) }, { phase: 'post-op-icu', date: d(-1) }], archived: false, createdAt: iso(-5), updatedAt: iso(-2) },
        { id: uid(), name: '冯国强', gender: 'male', age: 59, mrn: 'M010', bedNumber: '7', diagnosis: '二尖瓣腱索断裂重度关闭不全', comorbidities: [], admissionDate: d(-4), surgeryDate: d(-2), phase: 'post-op-icu', attendingDoctor: '刘医生', surgery: { surgeryType: 'MVR（成形环）', cpbTime: 95, crossClampTime: 68 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-2) }], tags: ['MVR'], notes: 'POD2，计划明日拔管', phaseHistory: [{ phase: 'pre-op', date: d(-4) }, { phase: 'surgery-day', date: d(-2) }, { phase: 'post-op-icu', date: d(-1) }], archived: false, createdAt: iso(-4), updatedAt: iso(-2) },
        // ── 病房监护 ──
        { id: uid(), name: '蒋建国', gender: 'male', age: 66, mrn: 'M011', bedNumber: '8', diagnosis: '冠心病双支病变', comorbidities: ['高血压', '糖尿病'], admissionDate: d(-10), surgeryDate: d(-7), phase: 'post-op-ward-monitor', attendingDoctor: '陈医生', surgery: { surgeryType: 'CABG×3', cpbTime: 108, crossClampTime: 78 }, tubes: [], tags: ['CABG'], notes: 'POD7，ICU转出第1天', phaseHistory: [{ phase: 'pre-op', date: d(-10) }, { phase: 'surgery-day', date: d(-7) }, { phase: 'post-op-icu', date: d(-6) }, { phase: 'post-op-ward-monitor', date: d(-1) }], archived: false, createdAt: iso(-10), updatedAt: iso(-1) },
        { id: uid(), name: '韩秀琴', gender: 'female', age: 70, mrn: 'M012', bedNumber: '9', diagnosis: '退行性主动脉瓣重度狭窄', comorbidities: [], admissionDate: d(-12), surgeryDate: d(-9), phase: 'post-op-ward-monitor', attendingDoctor: '刘医生', surgery: { surgeryType: 'TAVI', cathApproach: 'femoral' }, tubes: [], tags: ['TAVI'], notes: 'POD9，恢复良好', phaseHistory: [{ phase: 'pre-op', date: d(-12) }, { phase: 'surgery-day', date: d(-9) }, { phase: 'post-op-icu', date: d(-8) }, { phase: 'post-op-ward-monitor', date: d(-2) }], archived: false, createdAt: iso(-12), updatedAt: iso(-2) },
        // ── 术后病房 ──
        { id: uid(), name: '沈文博', gender: 'male', age: 52, mrn: 'M013', bedNumber: '10', diagnosis: '室间隔缺损（膜周部）', comorbidities: [], admissionDate: d(-15), surgeryDate: d(-12), phase: 'post-op-ward', attendingDoctor: '陈医生', surgery: { surgeryType: 'VSD修补术', cpbTime: 68, crossClampTime: 42 }, tubes: [], tags: ['VSD', '先心病'], notes: 'POD12，拟近日出院', phaseHistory: [{ phase: 'pre-op', date: d(-15) }, { phase: 'surgery-day', date: d(-12) }, { phase: 'post-op-icu', date: d(-11) }, { phase: 'post-op-ward-monitor', date: d(-9) }, { phase: 'post-op-ward', date: d(-5) }], archived: false, createdAt: iso(-15), updatedAt: iso(-5) },
        { id: uid(), name: '许雅琴', gender: 'female', age: 48, mrn: 'M014', bedNumber: '+3', diagnosis: '风湿性心瓣膜病双瓣联合病变', comorbidities: ['房颤'], admissionDate: d(-18), surgeryDate: d(-14), phase: 'post-op-ward', attendingDoctor: '陈医生', surgery: { surgeryType: 'MVR+AVR双瓣置换（机械瓣）', cpbTime: 178, crossClampTime: 132 }, tubes: [], tags: ['双瓣', '房颤'], notes: 'POD14，INR达标', phaseHistory: [{ phase: 'pre-op', date: d(-18) }, { phase: 'surgery-day', date: d(-14) }, { phase: 'post-op-icu', date: d(-13) }, { phase: 'post-op-ward-monitor', date: d(-10) }, { phase: 'post-op-ward', date: d(-6) }], archived: false, createdAt: iso(-18), updatedAt: iso(-6) },
        { id: uid(), name: '黄志远', gender: 'male', age: 75, mrn: 'M015', bedNumber: '11', diagnosis: '缺血性心肌病 EF 35%', comorbidities: ['糖尿病', 'CKD3'], admissionDate: d(-20), surgeryDate: d(-16), phase: 'post-op-ward', attendingDoctor: '刘医生', surgery: { surgeryType: 'CABG×4+左室成形', cpbTime: 210, crossClampTime: 155, cmrLgeSegments: 6 }, tubes: [], tags: ['CABG', '低EF', 'CKD'], notes: 'POD16，恢复缓慢', phaseHistory: [{ phase: 'pre-op', date: d(-20) }, { phase: 'surgery-day', date: d(-16) }, { phase: 'post-op-icu', date: d(-15) }, { phase: 'post-op-ward-monitor', date: d(-11) }, { phase: 'post-op-ward', date: d(-7) }], archived: false, createdAt: iso(-20), updatedAt: iso(-7) },
        // ── 转出 ──
        { id: uid(), name: '何永福', gender: 'male', age: 81, mrn: 'M016', bedNumber: 'Z2', diagnosis: '主动脉瓣狭窄+冠心病', comorbidities: ['高血压', '认知障碍'], admissionDate: d(-25), surgeryDate: d(-21), phase: 'transfer', attendingDoctor: '刘医生', surgery: { surgeryType: 'AVR（生物瓣）+CABG×2', cpbTime: 145, crossClampTime: 105 }, tubes: [], tags: ['AVR', '高龄'], notes: '转回当地医院康复', phaseHistory: [{ phase: 'pre-op', date: d(-25) }, { phase: 'surgery-day', date: d(-21) }, { phase: 'post-op-icu', date: d(-20) }, { phase: 'post-op-ward-monitor', date: d(-16) }, { phase: 'post-op-ward', date: d(-12) }, { phase: 'transfer', date: d(0) }], archived: false, createdAt: iso(-25), updatedAt: iso(0) },
        // ── 已出院 ──
        { id: uid(), name: '钱学军', gender: 'male', age: 56, mrn: 'M017', bedNumber: '12', diagnosis: '房间隔缺损（继发孔型）', comorbidities: [], admissionDate: d(-30), surgeryDate: d(-27), dischargeDate: d(-10), phase: 'discharged', attendingDoctor: '陈医生', surgery: { surgeryType: 'ASD封堵术（介入）' }, tubes: [], tags: ['ASD'], notes: '', phaseHistory: [{ phase: 'pre-op', date: d(-30) }, { phase: 'surgery-day', date: d(-27) }, { phase: 'post-op-icu', date: d(-26) }, { phase: 'post-op-ward-monitor', date: d(-24) }, { phase: 'post-op-ward', date: d(-20) }, { phase: 'discharged', date: d(-10) }], archived: true, createdAt: iso(-30), updatedAt: iso(-10) },
        { id: uid(), name: '谢淑芬', gender: 'female', age: 69, mrn: 'M018', bedNumber: '+4', diagnosis: '二尖瓣脱垂重度关闭不全', comorbidities: ['甲亢'], admissionDate: d(-35), surgeryDate: d(-32), dischargeDate: d(-8), phase: 'discharged', attendingDoctor: '陈医生', surgery: { surgeryType: 'MVR（成形环）+TVP', cpbTime: 102, crossClampTime: 72 }, tubes: [], tags: ['MVR'], notes: '术后1月复查', phaseHistory: [{ phase: 'pre-op', date: d(-35) }, { phase: 'surgery-day', date: d(-32) }, { phase: 'post-op-icu', date: d(-31) }, { phase: 'post-op-ward-monitor', date: d(-28) }, { phase: 'post-op-ward', date: d(-22) }, { phase: 'discharged', date: d(-8) }], archived: true, createdAt: iso(-35), updatedAt: iso(-8) },
        // ── CICU ──
        { id: uid(), name: '熊海龙', gender: 'male', age: 42, mrn: 'M019', bedNumber: 'CICU1', diagnosis: '急性心梗心源性休克', comorbidities: [], admissionDate: d(-2), surgeryDate: d(-1), phase: 'post-op-icu', attendingDoctor: '刘医生', surgery: { surgeryType: '急诊CABG×3+IABP', cpbTime: 185, crossClampTime: 115 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-1) }, { id: uid(), type: 'arterial-sheath', insertedAt: iso(-1) }, { id: uid(), type: 'ett', insertedAt: iso(-1) }, { id: uid(), type: 'pericardial-drain', insertedAt: iso(-1) }, { id: uid(), type: 'left-chest-tube', insertedAt: iso(-1) }], tags: ['急诊', 'IABP', '休克'], notes: 'POD1，IABP辅助，大剂量升压药', phaseHistory: [{ phase: 'pre-op', date: d(-2) }, { phase: 'surgery-day', date: d(-1) }, { phase: 'post-op-icu', date: d(0) }], archived: false, createdAt: iso(-2), updatedAt: iso(0) },
        { id: uid(), name: '马晓燕', gender: 'female', age: 38, mrn: 'M020', bedNumber: 'CICU2', diagnosis: '围产期心肌病重度心衰', comorbidities: ['产后3月'], admissionDate: d(-4), surgeryDate: d(-3), phase: 'post-op-icu', attendingDoctor: '陈医生', surgery: { surgeryType: 'LVAD（HeartMate 3）', cpbTime: 220 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-3) }, { id: uid(), type: 'ett', insertedAt: iso(-3) }, { id: uid(), type: 'pericardial-drain', insertedAt: iso(-3) }], tags: ['LVAD', '终末期心衰'], notes: 'POD3，LVAD稳定', phaseHistory: [{ phase: 'pre-op', date: d(-4) }, { phase: 'surgery-day', date: d(-3) }, { phase: 'post-op-icu', date: d(-2) }], archived: false, createdAt: iso(-4), updatedAt: iso(-2) },
        // ── NICU ──
        { id: uid(), name: '丁小宝', gender: 'male', age: 0, mrn: 'M021', bedNumber: 'NICU1', diagnosis: '完全性大动脉转位（TGA）', comorbidities: ['新生儿'], admissionDate: d(-7), surgeryDate: d(-5), phase: 'post-op-icu', attendingDoctor: '刘医生', surgery: { surgeryType: 'Switch手术', cpbTime: 165, crossClampTime: 120, dhcaTime: 18 }, tubes: [{ id: uid(), type: 'cvc', insertedAt: iso(-5) }, { id: uid(), type: 'ett', insertedAt: iso(-5) }, { id: uid(), type: 'pericardial-drain', insertedAt: iso(-5) }], tags: ['新生儿', 'TGA'], notes: 'POD5，胸骨延迟闭合', phaseHistory: [{ phase: 'pre-op', date: d(-7) }, { phase: 'surgery-day', date: d(-5) }, { phase: 'post-op-icu', date: d(-4) }], archived: false, createdAt: iso(-7), updatedAt: iso(-1) },
    ];
    await db.patients.bulkAdd(patients);
    // Rounding records for non-pre-op patients
    const records = [];
    for (const p of patients.filter(p => !p.archived && p.phase !== 'pre-op')) {
        const pods = p.surgeryDate ? Math.max(1, Math.floor((Date.now() - new Date(p.surgeryDate + 'T00:00:00').getTime()) / 86400000)) : 1;
        for (let pod = 1; pod <= Math.min(pods, 3); pod++) {
            const texts = {
                1: 'POD1：血流动力学稳定，引流量正常范围，尿量满意。继续血管活性药维持，计划明日评估拔管。',
                2: 'POD2：顺利拔除气管插管，SpO₂ 96%（鼻导管2L/min）。血管活性药减量中。胸管引流量较昨日明显减少。',
                3: 'POD3：生命体征平稳，血管活性药继续减量。加强利尿，液体负平衡良好。新发房颤已用药控制。',
            };
            records.push({ id: uid(), patientId: p.id, phase: p.phase, pod, session: 'am', labText: '', todos: [], detailsText: texts[pod] || `POD${pod}早查房：生命体征平稳`, status: 'completed', completedAt: iso(-pod + 1), createdAt: iso(-pod + 1), updatedAt: iso(-pod + 1) });
            records.push({ id: uid(), patientId: p.id, phase: p.phase, pod, session: 'pm', labText: '', todos: [], detailsText: `POD${pod}晚查房：夜间平稳，引流量正常`, status: 'completed', completedAt: iso(-pod + 1), createdAt: iso(-pod + 1), updatedAt: iso(-pod + 1) });
        }
    }
    await db.roundingRecords.bulkAdd(records);
    console.log(`✅ ${patients.length} 名患者 + ${records.length} 条查房记录`);
    window.location.reload();
}
window.seedData = seedData;
